name       : python-rectangle-packer
version    : 2.0.1
release    : 3
source     :
    - https://pypi.io/packages/source/r/rectangle-packer/rectangle-packer-2.0.1.tar.gz : dd8e70184d2af8a195d568e0c2c3cc197f0c94c2a477475411e5ea978c67b27d
license    : MIT
component  : programming.python
summary    : Rectangle packing Python module
description: |
    Pack a set of rectangles into a bounding box with minimum area.
builddeps  :
    - cython
build      : |
    %python3_setup
install    : |
    %python3_install
